name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REPOSITORY_URI: docker.io/${{ secrets.DOCKER_USERNAME }}/bayedilov-news-bot
      IMAGE_TAG: ${{ github.sha }}
      CONTAINER_NAME: bayedilov-news-bot

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: |
          docker build -t $REPOSITORY_URI:latest .
          docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - name: Push to Docker Hub
        run: |
          docker push $REPOSITORY_URI:latest
          docker push $REPOSITORY_URI:$IMAGE_TAG
      - name: Update running container
        run: |
          docker pull $REPOSITORY_URI:latest
          docker stop $CONTAINER_NAME || true
          docker rm $CONTAINER_NAME || true
          
          while [ "$(docker ps -a -q -f name=$CONTAINER_NAME)" ]; do
            echo "Waiting for container $CONTAINER_NAME to be removed..."
            sleep 1
          done
          
          docker run -d \
          -e TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }} \ 
          -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
          -e NEWS_API_KEY=${{ secrets.NEWS_API_KEY }} \
          --name $CONTAINER_NAME $REPOSITORY_URI:latest

      - name: Clean up Docker images and containers
        run: |
          docker system prune -f
          docker volume prune -f
