name: Docker Build and Push
run-name: ${{ gitea.actor }}/${{ gitea.repository }}/${{ gitea.branch }}/${{ gitea.run_number }}

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: |
          COMMIT_HASH=$(echo ${{ github.sha }} | cut -c 1-7)
          IMAGE_TAG=build-$(echo ${{ github.run_id }} | awk -F":" '{print $2}')
          REPOSITORY_URI=docker.io/${{ secrets.DOCKER_USERNAME }}/bayedilov-news-bot
          docker build -t $REPOSITORY_URI:latest .
          docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

      - name: Push the Docker image
        run: |
          REPOSITORY_URI=docker.io/${{ secrets.DOCKER_USERNAME }}/botnews
          IMAGE_TAG=build-$(echo ${{ gitea.run_number }} | awk -F":" '{print $2}')
          docker push $REPOSITORY_URI:latest
          docker push $REPOSITORY_URI:$IMAGE_TAG
